/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dji_gsdemo_myapplication_MainActivity */

#ifndef _Included_com_dji_gsdemo_myapplication_MainActivity
#define _Included_com_dji_gsdemo_myapplication_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dji_gsdemo_myapplication_MainActivity
 * Method:    getAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dji_gsdemo_myapplication_MainActivity_getAddress
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
